language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-4.9
            - cmake
      env:
         - FC=gfortran-4.9

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-5
            - cmake
      env:
         - FC=gfortran-5

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-6
            - cmake
      env:
        - FC=gfortran-6

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-7
            - cmake
      env:
        - FC=gfortran-7

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          packages:
            - cmake
      env:
        - FC=pgf90

before_install:
    - printenv  # just for debug info that could be helpful
    - ./.travis.sh

script:
  - mkdir build && cd build
  - cmake ../
  - make
